{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/example"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/example"]}],"hierarchy":{"paths":[[]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.baidu.Example\/documentation\/Example"},"sections":[],"metadata":{"role":"collection","modules":[{"name":"Example"}],"title":"Example","roleHeading":"Framework","symbolKind":"module","externalID":"Example"},"topicSections":[{"identifiers":["doc:\/\/com.baidu.Example\/documentation\/Example\/Person"],"title":"Structures"}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"}]}],"references":{"doc://com.baidu.Example/documentation/Example/Person":{"type":"topic","abstract":[{"text":"Person","type":"text"}],"identifier":"doc:\/\/com.baidu.Example\/documentation\/Example\/Person","navigatorTitle":[{"text":"Person","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Person","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/example\/person","title":"Person","role":"symbol"},"doc://com.baidu.Example/documentation/Example/ExampleVersionNumber":{"role":"symbol","title":"ExampleVersionNumber","fragments":[{"text":"ExampleVersionNumber","kind":"identifier"}],"type":"topic","url":"\/documentation\/example\/exampleversionnumber","abstract":[{"type":"text","text":"Project version number for Example."}],"kind":"symbol","identifier":"doc:\/\/com.baidu.Example\/documentation\/Example\/ExampleVersionNumber"},"doc://com.baidu.Example/documentation/Example/ExampleVersionString":{"title":"ExampleVersionString","abstract":[{"type":"text","text":"Project version string for Example."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/example\/exampleversionstring","fragments":[{"text":"ExampleVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.baidu.Example\/documentation\/Example\/ExampleVersionString"},"doc://com.baidu.Example/documentation/Example":{"kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.baidu.Example\/documentation\/Example","type":"topic","title":"Example","url":"\/documentation\/example"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"title":"Variables","identifiers":["doc:\/\/com.baidu.Example\/documentation\/Example\/ExampleVersionNumber","doc:\/\/com.baidu.Example\/documentation\/Example\/ExampleVersionString"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}